// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB07WBcN1pMqdOCPcTPd0geB0JOb7JXQes',
    appId: '1:1044605242848:web:7757047fd2b778b7f2ef85',
    messagingSenderId: '1044605242848',
    projectId: 'fir-fa078',
    authDomain: 'fir-fa078.firebaseapp.com',
    databaseURL: 'https://fir-fa078-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa078.appspot.com',
    measurementId: 'G-TV15JLX3VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWvtQC6Nv6EmMzoieq7ejdJuyUS7eJss',
    appId: '1:1044605242848:android:7c942a24825e4ba6f2ef85',
    messagingSenderId: '1044605242848',
    projectId: 'fir-fa078',
    databaseURL: 'https://fir-fa078-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fa078.appspot.com',
  );
}
